language: node_js

node_js:
  - "5"

services:
  - docker
  - mysql
sudo: required

env:
  - DATABASE_PASS=""


before_script:
  - git config --global user.email "andrfas@gmail.com"
  - git config --global user.name "Andrey Mikh"
  - sails lift

script:
  - grunt testServer