language: node_js

node_js:
  - "5"

services:
  - docker
  - mysql
sudo: required



before_script:
  - mysql -u root -e 'CREATE DATABASE rss_aggregator;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('59722795') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - sails lift &
  - sleep 10

script:
  - grunt testServer