language: node_js

node_js:
  - "5"

services:
  - docker
  - mysql
sudo: required

env:
  - DATABASE_PASS=""


before_script:
  - mysql -u root -e 'CREATE DATABASE rss_aggregator;'
  - sails lift &
  - sleep 10

script:
  - grunt testServer