language: node_js

node_js:
  - "5"

before_script:
  - git config --global user.email "anton.netudykhata@uptech.team"
  - git config --global user.name "Anton Netudykhata"
  - npm install -g grunt
  - npm install


script: 
  - grunt testServer
  - grunt jshint