language: node_js
sudo: required

node_js:
  - "5"

services:
  - mysql
  - docker


before_script:
  - git config --global user.email "andrfas@gmail.com"
  - git config --global user.name "Andrey Mikh"
  - npm install jasmine-node -g
  - docker build -t aggregator .
  - docker run -p 3306:3306 --name aggregator-mysql -e MYSQL_ROOT_PASSWORD=59722795 -e MYSQL_DATABASE=rss_aggregator  mysql:5.7
  - docker run -p 1337:1337  --link aggregator-mysql -e DATABASE_HOST=aggregator-mysql aggregator sails lift
