language: node_js

node_js:
  - "5"

services:
  - docker
  - mysql
sudo: required

env:
  - DATABASE_PASS=""


before_script:
  - git config --global user.email "andrfas@gmail.com"
  - git config --global user.name "Andrey Mikh"
  - mysql -u root -e 'CREATE DATABASE rss_aggregator;'

script:
  - grunt testServer